export const ResponseCode: { [key: string]: string } = {
  "00": "Success",
  "99": "General Error",
  "01": "Bad request",
  "02": "Page index isn't integer",
  "03": "Page index must be greater than or equar to 1",
  "04": "Page size isn't integer",
  "05": "Page index must be greater than or equar to 1",
  "06": "User existed",
  "09": "Send email error",
  "10": "Send SMS error",
  "11": "Username already exist. Please try another one.",
  "12": "Email already exist. Please try another one.",
  "13": "username wrong",
  "14": "User not existed",
  "15": "pass is weak",
  "16": "username or email exist in auth0",
  "17": "user is blocked",
  "18": "OTP is not correct.",
  "19": "Email not matching",
  "20": "Username accept number and character",
  "21": "Password must contain at least 8 characters, 1 number, 1 upper case and 1 special character - Length: 8 to 30",
  "22": "age invalid",
  "23": "Email address does not exist.",
  "24": "Password is not match",
  "25": "Password is incorrect",
  "26": "Email invalid",
  "27": `User  don't have  balance`,
  "28": "Coin not found",
  "29": "Can not get rate",
  "30": "Request wallet error",
  "31": "Not found network active",
  "32": "Referral code does not exist",
  "33": "Address is not found",
  "34": "INSUFFICIENT_BALANCE",
  "35": "ADDRESS_SENDER_WITHDRAW_NOT_FOUND",
  "36": "Can not withdraw",
  "37": "ADDRESS_DEPOSIT_NOT_FOUND",
  "38": "Price has changed by over 0.5% since the last refresh.\nClick the top right refresh button to get the new quote.",
  "39": "An unexpected error has occurred\nClick the top right refresh button to get the new quote.",
  "40": `NOT_ENOUGH_BALANCE = '40'.`,
  "41": `NOT_REACH_MIN_AMOUNT = '41'`,
  "42": `EXCEED_MAX_AMOUNT = '42'.`,
  "43": `INVALID_SWAP_INPUT = '43'.`,
  "44": `NOT_FOUND_FIXTURE = '44'.`,
  "45": `REQUEST_BETRADAR_ERROR = '45'.`,
  "46": `NOT_FOUND_SWAP_CONFIG = '46'.`,
  "47": `AMOUNT_IN_TOO_LOW = '47'.`,
  "48": `BET_FAILED = '48'.`,
  "49": `GAME_INACTIVE = '49'.`,
  "50": `FIXTURE_INACTIVE = '50'.`,
  "51": `TIME_OVER = '51'.`,
  "52": `INVALID_STAKE = '52'.`,
  "53": `INVALID_ODDS = '53'.`,
  "54": `CAN_NOT_PLACE_BET_TWICE = '54'.`,
  "55": `NOT_FOUND_BET_GAME = '55'.`,
  "56": `TIME_FIXTURE_NOT_IN_TIME_DIV= '56'.`,
  "58": `NOT_FOUND_MULTI_GAME = '58'.`,
  "59": `FANTASY_USER_EXISTS = '59'.`,
  "60": `BET_GAME_NOT_IN_FIXTURE = '60'.`,
  "61": `SPORT_BOOK_INACTIVE = '61'.`,
  "66": `CAN_NOT_MULTI_BET_SAME_FIXTURE = '66'.`,
  "68": `Incorrect password.`,
  "67": "Verification code  is not correct.",
  "69": "This account has been deactivated.",
  "74": "Round is pending",
  "80": "NOT_FOUND_CONFIGS",
  "83": "HOLD_AMOUNT_LESS_THAN_MIN_STAKE_CONFIG",
  "84": "HOLD_AMOUNT_GREATER_THAN_MAX_STAKE_CONFIG",
  "92": "NOT_FOUND_FYC",
  "96": "There was a problem placing your bets. Please try again or contact support.",
};
